version: "3.4"

services:
    web_service:
        image: digital_ocean_demo_v1
        container_name: digital_ocean_demo_v1
        restart: unless-stopped
        build: web_service
        ports:
            - 49153:49153
        command: gunicorn --config gunicorn_config.py wsgi:app
